# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Samuel Rosenshein
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Samuel Rosenshein's portfolio website showcasing projects and blog posts." # used by search engines

  # Header and footer text
  header_text: >
     <h1>Full-Stack Web Developer, Sports Lover, and Beer Enthusiast</h1>
     <small>Focus on React, Ruby on Rails, and AngularJS</small>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "srosenshein1@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: "srosenshein"
  google_plus:
  instagram: 
  linkedin:  "http://www.linkedin.com/in/srosenshein" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "samro7655"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]